### ISSUE TITLE
Castling rules are not implemented correctly

### ISSUE THREAD

**Issue by mordrax** [darrensiegel/elm-chess#1]
![image](https://cloud.githubusercontent.com/assets/4709169/20638090/ea619542-b3ef-11e6-8f31-5676e7be0204.png)

At this point of the game, I'm unable to move any pawn.

Also, I couldn't work out how to swap the king and castle, on the close side (two squares in between).

Nice work btw! I prolly should have picked something smaller like a chess game for my first elm app...

EDIT: Well that was silly... I was in check :P, still, not sure how to castle the king.

**Comment by darrensiegel** [comment]
I went back and did some additional testing and it looks like castling is working for me.  To initiate a castle move, select your King and if castling is still available you will see two squares highlighted for potential moves (on each side that castling is available). 

If are still seeing a problem see if you can get me a list of moves that led you to that board state.

**Comment by mordrax** [comment]
My moves are on the screenshot, pretty much after I moved the knight, bishop out of the way I tried to castle.

I vaguely remember not seeing the highlighted squares, but perhaps it's just that I don't know the rules of chess, happy to close this issue.

**Comment by darrensiegel** [comment]
I went and replayed your game (it is really helpful that the AI is deterministic!) and I confirmed that you should have been able to castle after move 13. The following is the game board at that point.

<img width="350" alt="castling" src="https://cloud.githubusercontent.com/assets/7431756/20863896/bcedd3a4-b9a9-11e6-9e70-ba751991b958.png">


I also noticed that the computer was able to castle illegally at move 10.  At that point the computer was in check, and the rules of chess state that one cannot check out of, through, or into check.

I'm going to rename this issue slightly to reflect that castling rules are not implemented correctly. 

Thanks again for the help!

**Comment by darrensiegel** [comment]
I pushed changes and have updated elm-chess.com to include fixes that now implement castling rules correctly.  Thanks again for checking this project out and for taking the time to file this issue.
