### ISSUE TITLE
Make it buildable on linux

### ISSUE THREAD

**Issue by jhrcek** [darrensiegel/elm-chess#3]
Hello,
first of all, kudos. Even though you say you don't have much experience with FP/Elm, the code is really readable and nicely structured.

But I had trouble building it on Linux (Fedora 24). I was getting errors like: I cannot find module 'Chess.FEN'.

Module 'Chess.Game' is trying to import it.

Potential problems could be:
  * Misspelled the module name

I had to rename the source files in the following way to be able to build it
1) rename sources/chess to sources/Chess
2) make filenames match the module names (e.g. rename fen.elm to FEN.elm etc.)
3) use the following command to build it: `elm make source/Chess/Game.elm --output elm.js` - it would be nice to have this build command in readme for people who would like to play with your sources.

**Comment by darrensiegel** [comment]
Hey thanks for filing this issue.  I am certainly going to make the changes that you have suggested.

**Comment by darrensiegel** [comment]
I have pushed some changes that simplify the directory structure and address the build issues that you ran into, so I'm going to close this issue.  I also added instructions to the README.  Thanks for the feedback.
