### ISSUE TITLE
Domain is down :(

### ISSUE THREAD

**Issue by SidneyNemzer** [darrensiegel/elm-chess#5]
The elm-chess.com domain no longer resolves

**Comment by darrensiegel** [comment]
I indeed let the rights to elm-chess.com domain expire.

But, I just realized the backing AWS S3 bucket is still there and still serves the assets for the game.

https://s3.amazonaws.com/elm-chess.com/index.html

I've updated the `README.md` to include this link instead of `elm-chess.com`
